from mongoengine import Document, StringField, EmailField, IntField


class Form(Document):
    email=EmailField(required=True)
    a1=StringField(required=True)
    a2=StringField(required=True)
    a3=StringField(required=True)
    a4=StringField(required=True)
    a5=StringField(required=True)
    a6=StringField(required=True)
    a7=StringField(required=True)
    a8=StringField(required=True)
    a9=StringField(required=True)
    a10=StringField(required=True)
    a11=StringField(required=True)
    a12=StringField(required=True)
    a13=StringField(required=True)
    a14=StringField(required=True)
    a15=StringField(required=True)
    a16=StringField(required=True)
    a17=StringField(required=True)
    a18=StringField(required=True)
    a19=StringField(required=True)
    a20=StringField(required=True)
    a21=StringField(required=True)
    a22=StringField(required=True)
    b1=StringField(required=True)
    b2=StringField(required=True)
    b3=StringField(required=True)
    b4=StringField(required=True)
    b5=StringField(required=True)
    b6=StringField(required=True)
    b7=StringField(required=True)
    b8=StringField(required=True)